### ISSUE TITLE
Printing table lists fails if table is null

### ISSUE THREAD

**Issue by crithead** [crithead/tablator#1]
The table columns that are just a change to generate X of Y cause an exception to be raised.

```
src/tablator.py -d ../tablator-data-add-dmg-2011-treasure lair-a --print
Lair Treasure Type A
--------------------
Traceback (most recent call last):
  File "/home/gene/src/tablator/src/tablator.py", line 175, in <module>
    tablator.table.print_plain(table_name)
  File "/home/gene/src/tablator/src/tablator/table.py", line 279, in print_plain
    name = get_table_name(column['table'])
  File "/home/gene/src/tablator/src/tablator/table.py", line 90, in get_table_name
    return load_table(table_name)['name']
  File "/home/gene/src/tablator/src/tablator/table.py", line 107, in load_table
    table = tablator.data.load(table_name)
  File "/home/gene/src/tablator/src/tablator/data.py", line 58, in load
    raise ValueError('table_name is None')
ValueError: table_name is None
```

Table Lists with no null tables print correctly.

**Comment by crithead** [comment]
Fixed with changes to table types
